[package]
name = "typespec-wasm-test"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "26.0.0"
wasmtime-wasi = "26.0.0"
tokio = { version = "1.0", features = ["full"] }

[[bin]]
name = "test-typespec-component"
path = "src/main.rs"
